### ISSUE TITLE
Missing Taper data in the stm file

### ISSUE THREAD

**Issue by GakenouOF** [hbelbo/stanfordclassicr#1]
I have been trying to use the stanfordclassicr to extract the .stm files. Part of the table expected is the taper data which is all diameter sections measured at 10cm interval. I couldn't get this information from the list of tibble extracted. This is also the same for the example file in this function. 

Please can you advice on how to get this data?

**Comment by hbelbo** [comment]
Hi GakenouOF!  Well it's there, but perhaps the terminology used is not good enough to be self explaining. If you run the example script in the readme file: 
stemdat <- read_stm_file(stmfiles[1]) 
Then the diameter vetor for each stem is stored in the "stems" dataset in the variable "stemdiav". Please take a look at the values you get here for each stem. It is simply a comma separated vector with the first, second, third etc diameter 
for the stem. In my example it is located here: stemdat$stems$stemdiav[2]

**Comment by GakenouOF** [comment]
Hello @hbelbo, thank you for your kind response. I have seen it in your example. But it is not in my data. I think there is a problem with the vars used to write the function and the vars in my data. I am going to attach an image of the stems file i got. Is there by any chance the vars used in writing your function was supposed to be the same for all Stanford data? I believe it is a standard and should be the same. 

**example of stem file extracted**

<img width="380" alt="image" src="https://user-images.githubusercontent.com/48384837/185853457-f08ff716-f08f-4a0d-a01b-ea07d24516c0.png">


For example when i tried extracting .pri files, i get this error

> Error in `dplyr::left_join()`:
! Join columns must be present in data.
x Problem with `v126t1`.

Also, when i tried to extract .pri files, i get this error

> Error in rep(1:length(replicator), replicator) : invalid 'times' argument
In addition: Warning message:
Unknown or uninitialised column: `v125t1`.

could this be an error from the machine data?

**Comment by hbelbo** [comment]
Hi @GakenouOF , 
Well, it is a standard but there are still quite many variants of how these reports are put together. It seems your pri reports do not include what is called product group definitions. I thought these was allways present, but i might have been wrong. I will modify the code in the pri2tables to accept this situation without making problems.

**Comment by GakenouOF** [comment]
Hi @hbelbo, 
Thank you for your kind response. I am not sure how the data were recorded on our side but i went through the files yesterday and i think something is wrong somewhere. I don't get the same column for all files. Like i showed in the attached file, some stem files had 5 columns. Most of them are not capturing the taper data column. I am not sure where to start the diagnosis from.

**Comment by hbelbo** [comment]
Hi @GakenouOF, i have updated the pri2tables, so you could replace your stanfordclassicr package with the new one here on github and see if it helps.

**Comment by hbelbo** [comment]
If you have problems reading an stm file just send it to me, helmer.belbo@nibio.no and i will have a look.

**Comment by GakenouOF** [comment]
Thank you @hbelbo, i will check it now
